version: '3.8'

services:
  backend:
    build: ./backend-iris
    container_name: iris-backend
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    
  frontend:
    build: ./frontend-iris
    container_name: iris-frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy